// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/zibbp/eros/ent/report"
	"github.com/zibbp/eros/ent/schema"
	"github.com/zibbp/eros/ent/script"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	reportFields := schema.Report{}.Fields()
	_ = reportFields
	// reportDescName is the schema descriptor for name field.
	reportDescName := reportFields[1].Descriptor()
	// report.NameValidator is a validator for the "name" field. It is called by the builders before save.
	report.NameValidator = reportDescName.Validators[0].(func(string) error)
	// reportDescCreatedAt is the schema descriptor for created_at field.
	reportDescCreatedAt := reportFields[4].Descriptor()
	// report.DefaultCreatedAt holds the default value on creation for the created_at field.
	report.DefaultCreatedAt = reportDescCreatedAt.Default.(func() time.Time)
	// reportDescUpdatedAt is the schema descriptor for updated_at field.
	reportDescUpdatedAt := reportFields[5].Descriptor()
	// report.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	report.DefaultUpdatedAt = reportDescUpdatedAt.Default.(func() time.Time)
	// report.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	report.UpdateDefaultUpdatedAt = reportDescUpdatedAt.UpdateDefault.(func() time.Time)
	// reportDescID is the schema descriptor for id field.
	reportDescID := reportFields[0].Descriptor()
	// report.DefaultID holds the default value on creation for the id field.
	report.DefaultID = reportDescID.Default.(func() uuid.UUID)
	scriptFields := schema.Script{}.Fields()
	_ = scriptFields
	// scriptDescName is the schema descriptor for name field.
	scriptDescName := scriptFields[1].Descriptor()
	// script.NameValidator is a validator for the "name" field. It is called by the builders before save.
	script.NameValidator = scriptDescName.Validators[0].(func(string) error)
	// scriptDescHostname is the schema descriptor for hostname field.
	scriptDescHostname := scriptFields[2].Descriptor()
	// script.HostnameValidator is a validator for the "hostname" field. It is called by the builders before save.
	script.HostnameValidator = scriptDescHostname.Validators[0].(func(string) error)
	// scriptDescNotify is the schema descriptor for notify field.
	scriptDescNotify := scriptFields[3].Descriptor()
	// script.DefaultNotify holds the default value on creation for the notify field.
	script.DefaultNotify = scriptDescNotify.Default.(bool)
	// scriptDescCreatedAt is the schema descriptor for created_at field.
	scriptDescCreatedAt := scriptFields[5].Descriptor()
	// script.DefaultCreatedAt holds the default value on creation for the created_at field.
	script.DefaultCreatedAt = scriptDescCreatedAt.Default.(func() time.Time)
	// scriptDescUpdatedAt is the schema descriptor for updated_at field.
	scriptDescUpdatedAt := scriptFields[6].Descriptor()
	// script.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	script.DefaultUpdatedAt = scriptDescUpdatedAt.Default.(func() time.Time)
	// script.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	script.UpdateDefaultUpdatedAt = scriptDescUpdatedAt.UpdateDefault.(func() time.Time)
	// scriptDescID is the schema descriptor for id field.
	scriptDescID := scriptFields[0].Descriptor()
	// script.DefaultID holds the default value on creation for the id field.
	script.DefaultID = scriptDescID.Default.(func() uuid.UUID)
}
